name: build

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
     - name: Build summary
       run: |
         echo 'Build complete'

  deploy-dev:
    name: deploy-dev
    uses: gidavies-org/reusable-viz/.github/workflows/deploy-dev.yml@main
    needs: build
    strategy:
        matrix:
          environment: [dev, staging, prod]
    with:
      environment: ${{ matrix.environment }}