name: deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  plan:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Summary
      run: echo 'Deploy to ${{ inputs.environment }} complete'