name: Deploy Dev

on:
  workflow_call:

jobs:
  plan:
    name: Plan
    uses: gidavies-org/reusable-viz/.github/workflows/plan.yml@main
    strategy:
      matrix:
        environment: [dev, staging, prod]
    with:
      environment: ${{ matrix.environment }}

  deploy:
    name: Deploy
    uses: gidavies-org/reusable-viz/.github/workflows/deploy.yml@main
    needs: plan
    strategy:
      matrix:
        environment: [dev, staging, prod]
    with:
      environment: ${{ matrix.environment }}