name: Deploy Dev

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  plan:
    name: Plan
    uses: gidavies-org/reusable-viz/.github/workflows/plan.yml@main
    with:
      environment: ${{ inputs.environment }}

  deploy:
    name: Deploy
    uses: gidavies-org/reusable-viz/.github/workflows/deploy.yml@main
    needs: plan
    with:
      environment: ${{ inputs.environment }}