name: plan

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        
jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest

    steps:
    - name: Plan Summary
      run: echo 'Plan for ${{ inputs.environment }} complete'